### ISSUE TITLE
Ошибка при запуске бота после сборки, тоже самое и на Heroku

### ISSUE THREAD

**Issue by TrippieNight** [nik9play/vk-music-bot#12]
TypeError: Cannot read property 'split' of undefined
     at Module.<anonymous> (/app/dist/main.js:1:3173)
     at o (/app/dist/main.js:1:119)
     at /app/dist/main.js:1:1137
     at Object.<anonymous> (/app/dist/main.js:1:1147)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
     at Module.load (internal/modules/cjs/loader.js:928:32)
     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
     at internal/main/run_main_module.js:17:47
 (node:31) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
     at Shard.onDeath (/app/node_modules/discord.js/src/sharding/Shard.js:155:16)
     at Object.onceWrapper (events.js:422:26)
     at Shard.emit (events.js:315:20)
     at Shard._handleExit (/app/node_modules/discord.js/src/sharding/Shard.js:371:10)
     at ChildProcess.emit (events.js:315:20)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
 (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 25)

**Comment by nik9play** [comment]
Видимо не стоит переменная со списком нод лавалинк

**Comment by levarar** [comment]
Та же ошибка, смогли исправить?

**Comment by nik9play** [comment]
Проверьте переменную окружения `LAVALINK_NODES`. Она должна быть в таком формате:
`название1,хост1,порт1,пароль1;название2,хост2,порт2,пароль2`

**Comment by TrippieNight** [comment]
> Та же ошибка, смогли исправить?

да, в index.js есть закомментированная часть, типо такой //const LavalinkServer = [{ name: 'vk-music-bot-1', host: 'localhost', port: 2333, auth: 'youshallnotpass' }], сотри выше lavalink servers и в new shoukaku в параметра тоже s сотри последнюю  у lavalink severs

**Comment by nik9play** [comment]
Проблема решена
